// Producer.idl : IDL source for Producer
//

// This file will be processed by the MIDL tool to
// produce the type library (Producer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(daf33656-4a53-47c6-89e5-c28e51e94dc3),
	dual,
	oleautomation,
	nonextensible,
	pointer_default(unique)
]
interface IGroup : IDispatch
{
	[id(1), helpstring("zero")]
	HRESULT GetZero([out, retval] LONG* value);

};
[
	uuid(a61e324a-02da-4ae8-b7e6-168a9cb1c7af),
	version(1.0),
]
library ProducerLib
{
	importlib("stdole2.tlb");
	[
		uuid(e7c4a90b-4368-48e5-820e-4b075bae1183)
	]
	coclass Field
	{
		[default] interface IGroup;
	};
};

import "shobjidl.idl";
